# Site settings
title: Instituto Mutirão
description: Uma rede de pessoas programando a democracia digital
analytics_id: UA-XXXXX-X
email: nucleo@nucleo.com.br

collections:
- apresentacao
- objetivos
- cases
- clientes
- depoimentos
- oss
- midia
- equipe

# Build settings
markdown: kramdown

gems: [jekyll-sass]
